webpack config changes for fixing build issue
nicksp/redux-webpack-es6-boilerplate pull request #33
Opened 2016-09-24 17:12 UTC by RanjithNair

This change is with respect to the build failing on mostly Windows systems. The issue has been discussed below :-
https://github.com/nicksp/redux-webpack-es6-boilerplate/issues/31

2016-09-24 21:58 UTC, nicksp commented on config/webpack.config.base.js
> +        include: path.resolve(__dirname, "../src/client/assets/javascripts"),
Can you please change quotes to be single quotes, since that's what i use in my codebase for strings?

2016-09-24 21:59 UTC, nicksp commented on config/webpack.config.development.js
> +          path.resolve(__dirname, "../src/client/scripts")
Can you please change quotes to be single quotes, since that's what i use in my codebase for strings?

2016-09-24 21:59 UTC, nicksp commented on config/webpack.config.production.js
> +          path.resolve(__dirname, "../src/client/scripts")
Can you please change quotes to be single quotes, since that's what i use in my codebase for strings?

2016-09-24 21:59 UTC, nicksp requested changes

2016-09-24 22:01 UTC, nicksp commented
Code changes LGTM, work nicely in my setup, just want some stylistic changes to be done.

2016-09-24 23:49 UTC, RanjithNair commented on config/webpack.config.production.js
> +          path.resolve(__dirname, "../src/client/scripts")
@nicksp Have made that change.

2016-09-25 00:50 UTC, RanjithNair reviewed
Replaced double quotes with single quotes

2016-09-25 00:51 UTC, RanjithNair commented
Webpack config changes.

2016-09-25 17:26 UTC, nicksp commented on config/webpack.config.production.js
> +          path.resolve(__dirname, "../src/client/scripts")
Thanks @RanjithNair

2016-09-25 17:26 UTC, nicksp approved these changes

2016-09-25 17:26 UTC, merged